package com.figo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PcbDesignStoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    public PcbDesignStoreExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPnIsNull() {
            addCriterion("PN is null");
            return (Criteria) this;
        }

        public Criteria andPnIsNotNull() {
            addCriterion("PN is not null");
            return (Criteria) this;
        }

        public Criteria andPnEqualTo(String value) {
            addCriterion("PN =", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnNotEqualTo(String value) {
            addCriterion("PN <>", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnGreaterThan(String value) {
            addCriterion("PN >", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnGreaterThanOrEqualTo(String value) {
            addCriterion("PN >=", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnLessThan(String value) {
            addCriterion("PN <", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnLessThanOrEqualTo(String value) {
            addCriterion("PN <=", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnLike(String value) {
            addCriterion("PN like", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnNotLike(String value) {
            addCriterion("PN not like", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnIn(List<String> values) {
            addCriterion("PN in", values, "pn");
            return (Criteria) this;
        }

        public Criteria andPnNotIn(List<String> values) {
            addCriterion("PN not in", values, "pn");
            return (Criteria) this;
        }

        public Criteria andPnBetween(String value1, String value2) {
            addCriterion("PN between", value1, value2, "pn");
            return (Criteria) this;
        }

        public Criteria andPnNotBetween(String value1, String value2) {
            addCriterion("PN not between", value1, value2, "pn");
            return (Criteria) this;
        }

        public Criteria andTempPnIsNull() {
            addCriterion("temp_PN is null");
            return (Criteria) this;
        }

        public Criteria andTempPnIsNotNull() {
            addCriterion("temp_PN is not null");
            return (Criteria) this;
        }

        public Criteria andTempPnEqualTo(String value) {
            addCriterion("temp_PN =", value, "tempPn");
            return (Criteria) this;
        }

        public Criteria andTempPnNotEqualTo(String value) {
            addCriterion("temp_PN <>", value, "tempPn");
            return (Criteria) this;
        }

        public Criteria andTempPnGreaterThan(String value) {
            addCriterion("temp_PN >", value, "tempPn");
            return (Criteria) this;
        }

        public Criteria andTempPnGreaterThanOrEqualTo(String value) {
            addCriterion("temp_PN >=", value, "tempPn");
            return (Criteria) this;
        }

        public Criteria andTempPnLessThan(String value) {
            addCriterion("temp_PN <", value, "tempPn");
            return (Criteria) this;
        }

        public Criteria andTempPnLessThanOrEqualTo(String value) {
            addCriterion("temp_PN <=", value, "tempPn");
            return (Criteria) this;
        }

        public Criteria andTempPnLike(String value) {
            addCriterion("temp_PN like", value, "tempPn");
            return (Criteria) this;
        }

        public Criteria andTempPnNotLike(String value) {
            addCriterion("temp_PN not like", value, "tempPn");
            return (Criteria) this;
        }

        public Criteria andTempPnIn(List<String> values) {
            addCriterion("temp_PN in", values, "tempPn");
            return (Criteria) this;
        }

        public Criteria andTempPnNotIn(List<String> values) {
            addCriterion("temp_PN not in", values, "tempPn");
            return (Criteria) this;
        }

        public Criteria andTempPnBetween(String value1, String value2) {
            addCriterion("temp_PN between", value1, value2, "tempPn");
            return (Criteria) this;
        }

        public Criteria andTempPnNotBetween(String value1, String value2) {
            addCriterion("temp_PN not between", value1, value2, "tempPn");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andVerIsNull() {
            addCriterion("ver is null");
            return (Criteria) this;
        }

        public Criteria andVerIsNotNull() {
            addCriterion("ver is not null");
            return (Criteria) this;
        }

        public Criteria andVerEqualTo(String value) {
            addCriterion("ver =", value, "ver");
            return (Criteria) this;
        }

        public Criteria andVerNotEqualTo(String value) {
            addCriterion("ver <>", value, "ver");
            return (Criteria) this;
        }

        public Criteria andVerGreaterThan(String value) {
            addCriterion("ver >", value, "ver");
            return (Criteria) this;
        }

        public Criteria andVerGreaterThanOrEqualTo(String value) {
            addCriterion("ver >=", value, "ver");
            return (Criteria) this;
        }

        public Criteria andVerLessThan(String value) {
            addCriterion("ver <", value, "ver");
            return (Criteria) this;
        }

        public Criteria andVerLessThanOrEqualTo(String value) {
            addCriterion("ver <=", value, "ver");
            return (Criteria) this;
        }

        public Criteria andVerLike(String value) {
            addCriterion("ver like", value, "ver");
            return (Criteria) this;
        }

        public Criteria andVerNotLike(String value) {
            addCriterion("ver not like", value, "ver");
            return (Criteria) this;
        }

        public Criteria andVerIn(List<String> values) {
            addCriterion("ver in", values, "ver");
            return (Criteria) this;
        }

        public Criteria andVerNotIn(List<String> values) {
            addCriterion("ver not in", values, "ver");
            return (Criteria) this;
        }

        public Criteria andVerBetween(String value1, String value2) {
            addCriterion("ver between", value1, value2, "ver");
            return (Criteria) this;
        }

        public Criteria andVerNotBetween(String value1, String value2) {
            addCriterion("ver not between", value1, value2, "ver");
            return (Criteria) this;
        }

        public Criteria andUserUploadIsNull() {
            addCriterion("user_upload is null");
            return (Criteria) this;
        }

        public Criteria andUserUploadIsNotNull() {
            addCriterion("user_upload is not null");
            return (Criteria) this;
        }

        public Criteria andUserUploadEqualTo(String value) {
            addCriterion("user_upload =", value, "userUpload");
            return (Criteria) this;
        }

        public Criteria andUserUploadNotEqualTo(String value) {
            addCriterion("user_upload <>", value, "userUpload");
            return (Criteria) this;
        }

        public Criteria andUserUploadGreaterThan(String value) {
            addCriterion("user_upload >", value, "userUpload");
            return (Criteria) this;
        }

        public Criteria andUserUploadGreaterThanOrEqualTo(String value) {
            addCriterion("user_upload >=", value, "userUpload");
            return (Criteria) this;
        }

        public Criteria andUserUploadLessThan(String value) {
            addCriterion("user_upload <", value, "userUpload");
            return (Criteria) this;
        }

        public Criteria andUserUploadLessThanOrEqualTo(String value) {
            addCriterion("user_upload <=", value, "userUpload");
            return (Criteria) this;
        }

        public Criteria andUserUploadLike(String value) {
            addCriterion("user_upload like", value, "userUpload");
            return (Criteria) this;
        }

        public Criteria andUserUploadNotLike(String value) {
            addCriterion("user_upload not like", value, "userUpload");
            return (Criteria) this;
        }

        public Criteria andUserUploadIn(List<String> values) {
            addCriterion("user_upload in", values, "userUpload");
            return (Criteria) this;
        }

        public Criteria andUserUploadNotIn(List<String> values) {
            addCriterion("user_upload not in", values, "userUpload");
            return (Criteria) this;
        }

        public Criteria andUserUploadBetween(String value1, String value2) {
            addCriterion("user_upload between", value1, value2, "userUpload");
            return (Criteria) this;
        }

        public Criteria andUserUploadNotBetween(String value1, String value2) {
            addCriterion("user_upload not between", value1, value2, "userUpload");
            return (Criteria) this;
        }

        public Criteria andDateUploadIsNull() {
            addCriterion("date_upload is null");
            return (Criteria) this;
        }

        public Criteria andDateUploadIsNotNull() {
            addCriterion("date_upload is not null");
            return (Criteria) this;
        }

        public Criteria andDateUploadEqualTo(Date value) {
            addCriterion("date_upload =", value, "dateUpload");
            return (Criteria) this;
        }

        public Criteria andDateUploadNotEqualTo(Date value) {
            addCriterion("date_upload <>", value, "dateUpload");
            return (Criteria) this;
        }

        public Criteria andDateUploadGreaterThan(Date value) {
            addCriterion("date_upload >", value, "dateUpload");
            return (Criteria) this;
        }

        public Criteria andDateUploadGreaterThanOrEqualTo(Date value) {
            addCriterion("date_upload >=", value, "dateUpload");
            return (Criteria) this;
        }

        public Criteria andDateUploadLessThan(Date value) {
            addCriterion("date_upload <", value, "dateUpload");
            return (Criteria) this;
        }

        public Criteria andDateUploadLessThanOrEqualTo(Date value) {
            addCriterion("date_upload <=", value, "dateUpload");
            return (Criteria) this;
        }

        public Criteria andDateUploadIn(List<Date> values) {
            addCriterion("date_upload in", values, "dateUpload");
            return (Criteria) this;
        }

        public Criteria andDateUploadNotIn(List<Date> values) {
            addCriterion("date_upload not in", values, "dateUpload");
            return (Criteria) this;
        }

        public Criteria andDateUploadBetween(Date value1, Date value2) {
            addCriterion("date_upload between", value1, value2, "dateUpload");
            return (Criteria) this;
        }

        public Criteria andDateUploadNotBetween(Date value1, Date value2) {
            addCriterion("date_upload not between", value1, value2, "dateUpload");
            return (Criteria) this;
        }

        public Criteria andUserModifiedIsNull() {
            addCriterion("user_modified is null");
            return (Criteria) this;
        }

        public Criteria andUserModifiedIsNotNull() {
            addCriterion("user_modified is not null");
            return (Criteria) this;
        }

        public Criteria andUserModifiedEqualTo(String value) {
            addCriterion("user_modified =", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedNotEqualTo(String value) {
            addCriterion("user_modified <>", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedGreaterThan(String value) {
            addCriterion("user_modified >", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedGreaterThanOrEqualTo(String value) {
            addCriterion("user_modified >=", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedLessThan(String value) {
            addCriterion("user_modified <", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedLessThanOrEqualTo(String value) {
            addCriterion("user_modified <=", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedLike(String value) {
            addCriterion("user_modified like", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedNotLike(String value) {
            addCriterion("user_modified not like", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedIn(List<String> values) {
            addCriterion("user_modified in", values, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedNotIn(List<String> values) {
            addCriterion("user_modified not in", values, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedBetween(String value1, String value2) {
            addCriterion("user_modified between", value1, value2, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedNotBetween(String value1, String value2) {
            addCriterion("user_modified not between", value1, value2, "userModified");
            return (Criteria) this;
        }

        public Criteria andDateModifiedIsNull() {
            addCriterion("date_modified is null");
            return (Criteria) this;
        }

        public Criteria andDateModifiedIsNotNull() {
            addCriterion("date_modified is not null");
            return (Criteria) this;
        }

        public Criteria andDateModifiedEqualTo(Date value) {
            addCriterion("date_modified =", value, "dateModified");
            return (Criteria) this;
        }

        public Criteria andDateModifiedNotEqualTo(Date value) {
            addCriterion("date_modified <>", value, "dateModified");
            return (Criteria) this;
        }

        public Criteria andDateModifiedGreaterThan(Date value) {
            addCriterion("date_modified >", value, "dateModified");
            return (Criteria) this;
        }

        public Criteria andDateModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("date_modified >=", value, "dateModified");
            return (Criteria) this;
        }

        public Criteria andDateModifiedLessThan(Date value) {
            addCriterion("date_modified <", value, "dateModified");
            return (Criteria) this;
        }

        public Criteria andDateModifiedLessThanOrEqualTo(Date value) {
            addCriterion("date_modified <=", value, "dateModified");
            return (Criteria) this;
        }

        public Criteria andDateModifiedIn(List<Date> values) {
            addCriterion("date_modified in", values, "dateModified");
            return (Criteria) this;
        }

        public Criteria andDateModifiedNotIn(List<Date> values) {
            addCriterion("date_modified not in", values, "dateModified");
            return (Criteria) this;
        }

        public Criteria andDateModifiedBetween(Date value1, Date value2) {
            addCriterion("date_modified between", value1, value2, "dateModified");
            return (Criteria) this;
        }

        public Criteria andDateModifiedNotBetween(Date value1, Date value2) {
            addCriterion("date_modified not between", value1, value2, "dateModified");
            return (Criteria) this;
        }

        public Criteria andApproverIsNull() {
            addCriterion("approver is null");
            return (Criteria) this;
        }

        public Criteria andApproverIsNotNull() {
            addCriterion("approver is not null");
            return (Criteria) this;
        }

        public Criteria andApproverEqualTo(String value) {
            addCriterion("approver =", value, "approver");
            return (Criteria) this;
        }

        public Criteria andApproverNotEqualTo(String value) {
            addCriterion("approver <>", value, "approver");
            return (Criteria) this;
        }

        public Criteria andApproverGreaterThan(String value) {
            addCriterion("approver >", value, "approver");
            return (Criteria) this;
        }

        public Criteria andApproverGreaterThanOrEqualTo(String value) {
            addCriterion("approver >=", value, "approver");
            return (Criteria) this;
        }

        public Criteria andApproverLessThan(String value) {
            addCriterion("approver <", value, "approver");
            return (Criteria) this;
        }

        public Criteria andApproverLessThanOrEqualTo(String value) {
            addCriterion("approver <=", value, "approver");
            return (Criteria) this;
        }

        public Criteria andApproverLike(String value) {
            addCriterion("approver like", value, "approver");
            return (Criteria) this;
        }

        public Criteria andApproverNotLike(String value) {
            addCriterion("approver not like", value, "approver");
            return (Criteria) this;
        }

        public Criteria andApproverIn(List<String> values) {
            addCriterion("approver in", values, "approver");
            return (Criteria) this;
        }

        public Criteria andApproverNotIn(List<String> values) {
            addCriterion("approver not in", values, "approver");
            return (Criteria) this;
        }

        public Criteria andApproverBetween(String value1, String value2) {
            addCriterion("approver between", value1, value2, "approver");
            return (Criteria) this;
        }

        public Criteria andApproverNotBetween(String value1, String value2) {
            addCriterion("approver not between", value1, value2, "approver");
            return (Criteria) this;
        }

        public Criteria andDateApprovedIsNull() {
            addCriterion("date_approved is null");
            return (Criteria) this;
        }

        public Criteria andDateApprovedIsNotNull() {
            addCriterion("date_approved is not null");
            return (Criteria) this;
        }

        public Criteria andDateApprovedEqualTo(Date value) {
            addCriterion("date_approved =", value, "dateApproved");
            return (Criteria) this;
        }

        public Criteria andDateApprovedNotEqualTo(Date value) {
            addCriterion("date_approved <>", value, "dateApproved");
            return (Criteria) this;
        }

        public Criteria andDateApprovedGreaterThan(Date value) {
            addCriterion("date_approved >", value, "dateApproved");
            return (Criteria) this;
        }

        public Criteria andDateApprovedGreaterThanOrEqualTo(Date value) {
            addCriterion("date_approved >=", value, "dateApproved");
            return (Criteria) this;
        }

        public Criteria andDateApprovedLessThan(Date value) {
            addCriterion("date_approved <", value, "dateApproved");
            return (Criteria) this;
        }

        public Criteria andDateApprovedLessThanOrEqualTo(Date value) {
            addCriterion("date_approved <=", value, "dateApproved");
            return (Criteria) this;
        }

        public Criteria andDateApprovedIn(List<Date> values) {
            addCriterion("date_approved in", values, "dateApproved");
            return (Criteria) this;
        }

        public Criteria andDateApprovedNotIn(List<Date> values) {
            addCriterion("date_approved not in", values, "dateApproved");
            return (Criteria) this;
        }

        public Criteria andDateApprovedBetween(Date value1, Date value2) {
            addCriterion("date_approved between", value1, value2, "dateApproved");
            return (Criteria) this;
        }

        public Criteria andDateApprovedNotBetween(Date value1, Date value2) {
            addCriterion("date_approved not between", value1, value2, "dateApproved");
            return (Criteria) this;
        }

        public Criteria andPathSchIsNull() {
            addCriterion("path_sch is null");
            return (Criteria) this;
        }

        public Criteria andPathSchIsNotNull() {
            addCriterion("path_sch is not null");
            return (Criteria) this;
        }

        public Criteria andPathSchEqualTo(String value) {
            addCriterion("path_sch =", value, "pathSch");
            return (Criteria) this;
        }

        public Criteria andPathSchNotEqualTo(String value) {
            addCriterion("path_sch <>", value, "pathSch");
            return (Criteria) this;
        }

        public Criteria andPathSchGreaterThan(String value) {
            addCriterion("path_sch >", value, "pathSch");
            return (Criteria) this;
        }

        public Criteria andPathSchGreaterThanOrEqualTo(String value) {
            addCriterion("path_sch >=", value, "pathSch");
            return (Criteria) this;
        }

        public Criteria andPathSchLessThan(String value) {
            addCriterion("path_sch <", value, "pathSch");
            return (Criteria) this;
        }

        public Criteria andPathSchLessThanOrEqualTo(String value) {
            addCriterion("path_sch <=", value, "pathSch");
            return (Criteria) this;
        }

        public Criteria andPathSchLike(String value) {
            addCriterion("path_sch like", value, "pathSch");
            return (Criteria) this;
        }

        public Criteria andPathSchNotLike(String value) {
            addCriterion("path_sch not like", value, "pathSch");
            return (Criteria) this;
        }

        public Criteria andPathSchIn(List<String> values) {
            addCriterion("path_sch in", values, "pathSch");
            return (Criteria) this;
        }

        public Criteria andPathSchNotIn(List<String> values) {
            addCriterion("path_sch not in", values, "pathSch");
            return (Criteria) this;
        }

        public Criteria andPathSchBetween(String value1, String value2) {
            addCriterion("path_sch between", value1, value2, "pathSch");
            return (Criteria) this;
        }

        public Criteria andPathSchNotBetween(String value1, String value2) {
            addCriterion("path_sch not between", value1, value2, "pathSch");
            return (Criteria) this;
        }

        public Criteria andPathLayoutIsNull() {
            addCriterion("path_layout is null");
            return (Criteria) this;
        }

        public Criteria andPathLayoutIsNotNull() {
            addCriterion("path_layout is not null");
            return (Criteria) this;
        }

        public Criteria andPathLayoutEqualTo(String value) {
            addCriterion("path_layout =", value, "pathLayout");
            return (Criteria) this;
        }

        public Criteria andPathLayoutNotEqualTo(String value) {
            addCriterion("path_layout <>", value, "pathLayout");
            return (Criteria) this;
        }

        public Criteria andPathLayoutGreaterThan(String value) {
            addCriterion("path_layout >", value, "pathLayout");
            return (Criteria) this;
        }

        public Criteria andPathLayoutGreaterThanOrEqualTo(String value) {
            addCriterion("path_layout >=", value, "pathLayout");
            return (Criteria) this;
        }

        public Criteria andPathLayoutLessThan(String value) {
            addCriterion("path_layout <", value, "pathLayout");
            return (Criteria) this;
        }

        public Criteria andPathLayoutLessThanOrEqualTo(String value) {
            addCriterion("path_layout <=", value, "pathLayout");
            return (Criteria) this;
        }

        public Criteria andPathLayoutLike(String value) {
            addCriterion("path_layout like", value, "pathLayout");
            return (Criteria) this;
        }

        public Criteria andPathLayoutNotLike(String value) {
            addCriterion("path_layout not like", value, "pathLayout");
            return (Criteria) this;
        }

        public Criteria andPathLayoutIn(List<String> values) {
            addCriterion("path_layout in", values, "pathLayout");
            return (Criteria) this;
        }

        public Criteria andPathLayoutNotIn(List<String> values) {
            addCriterion("path_layout not in", values, "pathLayout");
            return (Criteria) this;
        }

        public Criteria andPathLayoutBetween(String value1, String value2) {
            addCriterion("path_layout between", value1, value2, "pathLayout");
            return (Criteria) this;
        }

        public Criteria andPathLayoutNotBetween(String value1, String value2) {
            addCriterion("path_layout not between", value1, value2, "pathLayout");
            return (Criteria) this;
        }

        public Criteria andPathGerberIsNull() {
            addCriterion("path_gerber is null");
            return (Criteria) this;
        }

        public Criteria andPathGerberIsNotNull() {
            addCriterion("path_gerber is not null");
            return (Criteria) this;
        }

        public Criteria andPathGerberEqualTo(String value) {
            addCriterion("path_gerber =", value, "pathGerber");
            return (Criteria) this;
        }

        public Criteria andPathGerberNotEqualTo(String value) {
            addCriterion("path_gerber <>", value, "pathGerber");
            return (Criteria) this;
        }

        public Criteria andPathGerberGreaterThan(String value) {
            addCriterion("path_gerber >", value, "pathGerber");
            return (Criteria) this;
        }

        public Criteria andPathGerberGreaterThanOrEqualTo(String value) {
            addCriterion("path_gerber >=", value, "pathGerber");
            return (Criteria) this;
        }

        public Criteria andPathGerberLessThan(String value) {
            addCriterion("path_gerber <", value, "pathGerber");
            return (Criteria) this;
        }

        public Criteria andPathGerberLessThanOrEqualTo(String value) {
            addCriterion("path_gerber <=", value, "pathGerber");
            return (Criteria) this;
        }

        public Criteria andPathGerberLike(String value) {
            addCriterion("path_gerber like", value, "pathGerber");
            return (Criteria) this;
        }

        public Criteria andPathGerberNotLike(String value) {
            addCriterion("path_gerber not like", value, "pathGerber");
            return (Criteria) this;
        }

        public Criteria andPathGerberIn(List<String> values) {
            addCriterion("path_gerber in", values, "pathGerber");
            return (Criteria) this;
        }

        public Criteria andPathGerberNotIn(List<String> values) {
            addCriterion("path_gerber not in", values, "pathGerber");
            return (Criteria) this;
        }

        public Criteria andPathGerberBetween(String value1, String value2) {
            addCriterion("path_gerber between", value1, value2, "pathGerber");
            return (Criteria) this;
        }

        public Criteria andPathGerberNotBetween(String value1, String value2) {
            addCriterion("path_gerber not between", value1, value2, "pathGerber");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawIsNull() {
            addCriterion("path_pcbdraw is null");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawIsNotNull() {
            addCriterion("path_pcbdraw is not null");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawEqualTo(String value) {
            addCriterion("path_pcbdraw =", value, "pathPcbdraw");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawNotEqualTo(String value) {
            addCriterion("path_pcbdraw <>", value, "pathPcbdraw");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawGreaterThan(String value) {
            addCriterion("path_pcbdraw >", value, "pathPcbdraw");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawGreaterThanOrEqualTo(String value) {
            addCriterion("path_pcbdraw >=", value, "pathPcbdraw");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawLessThan(String value) {
            addCriterion("path_pcbdraw <", value, "pathPcbdraw");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawLessThanOrEqualTo(String value) {
            addCriterion("path_pcbdraw <=", value, "pathPcbdraw");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawLike(String value) {
            addCriterion("path_pcbdraw like", value, "pathPcbdraw");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawNotLike(String value) {
            addCriterion("path_pcbdraw not like", value, "pathPcbdraw");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawIn(List<String> values) {
            addCriterion("path_pcbdraw in", values, "pathPcbdraw");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawNotIn(List<String> values) {
            addCriterion("path_pcbdraw not in", values, "pathPcbdraw");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawBetween(String value1, String value2) {
            addCriterion("path_pcbdraw between", value1, value2, "pathPcbdraw");
            return (Criteria) this;
        }

        public Criteria andPathPcbdrawNotBetween(String value1, String value2) {
            addCriterion("path_pcbdraw not between", value1, value2, "pathPcbdraw");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistIsNull() {
            addCriterion("path_pcbchecklist is null");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistIsNotNull() {
            addCriterion("path_pcbchecklist is not null");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistEqualTo(String value) {
            addCriterion("path_pcbchecklist =", value, "pathPcbchecklist");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistNotEqualTo(String value) {
            addCriterion("path_pcbchecklist <>", value, "pathPcbchecklist");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistGreaterThan(String value) {
            addCriterion("path_pcbchecklist >", value, "pathPcbchecklist");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistGreaterThanOrEqualTo(String value) {
            addCriterion("path_pcbchecklist >=", value, "pathPcbchecklist");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistLessThan(String value) {
            addCriterion("path_pcbchecklist <", value, "pathPcbchecklist");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistLessThanOrEqualTo(String value) {
            addCriterion("path_pcbchecklist <=", value, "pathPcbchecklist");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistLike(String value) {
            addCriterion("path_pcbchecklist like", value, "pathPcbchecklist");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistNotLike(String value) {
            addCriterion("path_pcbchecklist not like", value, "pathPcbchecklist");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistIn(List<String> values) {
            addCriterion("path_pcbchecklist in", values, "pathPcbchecklist");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistNotIn(List<String> values) {
            addCriterion("path_pcbchecklist not in", values, "pathPcbchecklist");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistBetween(String value1, String value2) {
            addCriterion("path_pcbchecklist between", value1, value2, "pathPcbchecklist");
            return (Criteria) this;
        }

        public Criteria andPathPcbchecklistNotBetween(String value1, String value2) {
            addCriterion("path_pcbchecklist not between", value1, value2, "pathPcbchecklist");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pcb_design_store
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pcb_design_store
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}