package com.figo.model;

public class VUserRight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_right.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_right.role_status
     *
     * @mbggenerated
     */
    private Integer roleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_right.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_right.role_system
     *
     * @mbggenerated
     */
    private String roleSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_right.role_rights_id
     *
     * @mbggenerated
     */
    private Integer roleRightsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_right.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_right.right_id
     *
     * @mbggenerated
     */
    private Integer rightId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_right.all_rights_id
     *
     * @mbggenerated
     */
    private Integer allRightsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_right.right_status
     *
     * @mbggenerated
     */
    private Short rightStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_right.rights
     *
     * @mbggenerated
     */
    private String rights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_right.system
     *
     * @mbggenerated
     */
    private String system;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_right.id
     *
     * @return the value of v_user_right.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_right.id
     *
     * @param id the value for v_user_right.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_right.role_status
     *
     * @return the value of v_user_right.role_status
     *
     * @mbggenerated
     */
    public Integer getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_right.role_status
     *
     * @param roleStatus the value for v_user_right.role_status
     *
     * @mbggenerated
     */
    public void setRoleStatus(Integer roleStatus) {
        this.roleStatus = roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_right.name
     *
     * @return the value of v_user_right.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_right.name
     *
     * @param name the value for v_user_right.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_right.role_system
     *
     * @return the value of v_user_right.role_system
     *
     * @mbggenerated
     */
    public String getRoleSystem() {
        return roleSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_right.role_system
     *
     * @param roleSystem the value for v_user_right.role_system
     *
     * @mbggenerated
     */
    public void setRoleSystem(String roleSystem) {
        this.roleSystem = roleSystem == null ? null : roleSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_right.role_rights_id
     *
     * @return the value of v_user_right.role_rights_id
     *
     * @mbggenerated
     */
    public Integer getRoleRightsId() {
        return roleRightsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_right.role_rights_id
     *
     * @param roleRightsId the value for v_user_right.role_rights_id
     *
     * @mbggenerated
     */
    public void setRoleRightsId(Integer roleRightsId) {
        this.roleRightsId = roleRightsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_right.role_id
     *
     * @return the value of v_user_right.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_right.role_id
     *
     * @param roleId the value for v_user_right.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_right.right_id
     *
     * @return the value of v_user_right.right_id
     *
     * @mbggenerated
     */
    public Integer getRightId() {
        return rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_right.right_id
     *
     * @param rightId the value for v_user_right.right_id
     *
     * @mbggenerated
     */
    public void setRightId(Integer rightId) {
        this.rightId = rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_right.all_rights_id
     *
     * @return the value of v_user_right.all_rights_id
     *
     * @mbggenerated
     */
    public Integer getAllRightsId() {
        return allRightsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_right.all_rights_id
     *
     * @param allRightsId the value for v_user_right.all_rights_id
     *
     * @mbggenerated
     */
    public void setAllRightsId(Integer allRightsId) {
        this.allRightsId = allRightsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_right.right_status
     *
     * @return the value of v_user_right.right_status
     *
     * @mbggenerated
     */
    public Short getRightStatus() {
        return rightStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_right.right_status
     *
     * @param rightStatus the value for v_user_right.right_status
     *
     * @mbggenerated
     */
    public void setRightStatus(Short rightStatus) {
        this.rightStatus = rightStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_right.rights
     *
     * @return the value of v_user_right.rights
     *
     * @mbggenerated
     */
    public String getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_right.rights
     *
     * @param rights the value for v_user_right.rights
     *
     * @mbggenerated
     */
    public void setRights(String rights) {
        this.rights = rights == null ? null : rights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_right.system
     *
     * @return the value of v_user_right.system
     *
     * @mbggenerated
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_right.system
     *
     * @param system the value for v_user_right.system
     *
     * @mbggenerated
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }
}