package com.figo.dao;

import com.figo.model.VUserRight;
import com.figo.model.VUserRightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VUserRightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_right
     *
     * @mbggenerated
     */
    int countByExample(VUserRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_right
     *
     * @mbggenerated
     */
    int deleteByExample(VUserRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_right
     *
     * @mbggenerated
     */
    int insert(VUserRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_right
     *
     * @mbggenerated
     */
    int insertSelective(VUserRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_right
     *
     * @mbggenerated
     */
    List<VUserRight> selectByExample(VUserRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_right
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VUserRight record, @Param("example") VUserRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_right
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VUserRight record, @Param("example") VUserRightExample example);

    List<String>getRightsByID(@Param("role_id") int role_id,@Param("system") String system);
}